export const PATHS = {
    HOME: {route:'/', name:'home'},
    SCHEDULE: {route:'/schedule', name:'schedule'},
    DRIVERS: {route: '/drivers', name: 'drivers'}
}

export const getRoute= (pathname) => {
    if (pathname === PATHS.HOME.route) return PATHS.HOME.name
    else return pathname.substr(1)
}

export const countries = [
    {nat:"Abkhazian", code: "ab"},
    {nat:"Australian", code: "au"},
    {nat:"Afar", code: "aa"},
    {nat:"Afrikaans", code: "af"},
    {nat:"Akan", code: "ak"},
    {nat:"Albanian", code: "sq"},
    {nat:"Amharic", code: "am"},
    {nat:"Arabic", code: "ar"},
    {nat:"Aragonese", code: "an"},
    {nat:"Armenian", code: "hy"},
    {nat:"Assamese", code: "as"},
    {nat:"Austrian", code: "at"},
    {nat:"Avaric", code: "av"},
    {nat:"Avestan", code: "ae"},
    {nat:"Aymara", code: "ay"},
    {nat:"Azerbaijani", code: "az"},
    {nat:"Bambara", code: "bm"},
    {nat:"Bashkir", code: "ba"},
    {nat:"Basque", code: "eu"},
    {nat:"Belarusian, Belgian", code: "be"},
    {nat:"Bengali", code: "bn"},
    {nat:"Bislama", code: "bi"},
    {nat:"Bosnian", code: "bs"},
    {nat:"Breton, Brazilian", code: "br"},
    {nat:"Bulgarian", code: "bg"},
    {nat:"Burmese", code: "my"},
    {nat:"Canadian", code:"ca"},
    {nat:"Catalan, Valencian", code: "ca"},
    {nat:"Chamorro, Swiss", code: "ch"},
    {nat:"Chechen", code: "ce"},
    {nat:"Chichewa, Chewa, Nyanja", code: "ny"},
    {nat:"Chinese", code: "zh"},
    {nat:"Chuvash", code: "cv"},
    {nat:"Cornish", code: "kw"},
    {nat:"Corsican", code: "co"},
    {nat:"Cree", code: "cr"},
    {nat:"Croatian", code: "hr"},
    {nat:"Czech", code: "cs"},
    {nat:"Danish", code: "dk"},
    {nat:"Divehi, Dhivehi, Maldivian", code: "dv"},
    {nat:"Dutch, Flemish", code: "nl"},
    {nat:"Dzongkha", code: "dz"},
    {nat:"English, British", code: "gb"},
    {nat:"Esperanto", code: "eo"},
    {nat:"Estonian", code: "et"},
    {nat:"Ewe", code: "ee"},
    {nat:"Faroese", code: "fo"},
    {nat:"Fijian", code: "fj"},
    {nat:"Finnish", code: "fi"},
    {nat:"French", code: "fr"},
    {nat:"Fulah", code: "ff"},
    {nat:"Galician", code: "gl"},
    {nat:"Georgian", code: "ka"},
    {nat:"German", code: "de"},
    {nat:"Greek, Modern (1453–)", code: "el"},
    {nat:"Guarani", code: "gn"},
    {nat:"Gujarati", code: "gu"},
    {nat:"Haitian, Haitian Creole", code: "ht"},
    {nat:"Hausa", code: "ha"},
    {nat:"Hebrew", code: "he"},
    {nat:"Herero", code: "hz"},
    {nat:"Hindi", code: "hi"},
    {nat:"Hiri Motu", code: "ho"},
    {nat:"Hungarian", code: "hu"},
    {nat:"Interlingua (International Auxiliary Language Association)", code: "ia"},
    {nat:"Indonesian", code: "id"},
    {nat:"Indian", code: "in"},
    {nat:"Interlingue, Occidental", code: "ie"},
    {nat:"Irish", code: "ga"},
    {nat:"Igbo", code: "ig"},
    {nat:"Inupiaq", code: "ik"},
    {nat:"Ido", code: "io"},
    {nat:"Icelandic", code: "is"},
    {nat:"Italian", code: "it"},
    {nat:"Inuktitut", code: "iu"},
    {nat:"Japanese", code: "jp"},
    {nat:"Javanese", code: "jv"},
    {nat:"Kalaallisut, Greenlandic", code: "kl"},
    {nat:"Kannada", code: "kn"},
    {nat:"Kanuri", code: "kr"},
    {nat:"Kashmiri", code: "ks"},
    {nat:"Kazakh", code: "kk"},
    {nat:"Central Khmer", code: "km"},
    {nat:"Kikuyu, Gikuyu", code: "ki"},
    {nat:"Kinyarwanda", code: "rw"},
    {nat:"Kirghiz, Kyrgyz", code: "ky"},
    {nat:"Komi", code: "kv"},
    {nat:"Kongo", code: "kg"},
    {nat:"Korean", code: "ko"},
    {nat:"Kurdish", code: "ku"},
    {nat:"Kuanyama, Kwanyama", code: "kj"},
    {nat:"Latin", code: "la"},
    {nat:"Luxembourgish, Letzeburgesch", code: "lb"},
    {nat:"Ganda", code: "lg"},
    {nat:"Limburgan, Limburger, Limburgish", code: "li"},
    {nat:"Lingala", code: "ln"},
    {nat:"Lao", code: "lo"},
    {nat:"Lithuanian", code: "lt"},
    {nat:"Luba-Katanga", code: "lu"},
    {nat:"Latvian", code: "lv"},
    {nat:"Manx", code: "gv"},
    {nat:"Macedonian", code: "mk"},
    {nat:"Monaco, Monegasque", code: "mc"},
    {nat:"Malagasy", code: "mg"},
    {nat:"Malay", code: "ms"},
    {nat:"Malayalam", code: "ml"},
    {nat:"Maltese", code: "mt"},
    {nat:"Maori", code: "mi"},
    {nat:"Marathi", code: "mr"},
    {nat:"Mexican, Mexico", code: "mx"},
    {nat:"Marshallese", code: "mh"},
    {nat:"Mongolian", code: "mn"},
    {nat:"Nauru", code: "na"},
    {nat:"Navajo, Navaho", code: "nv"},
    {nat:"New Zealander", code: "nz"},
    {nat:"North Ndebele", code: "nd"},
    {nat:"Nepali", code: "ne"},
    {nat:"Ndonga", code: "ng"},
    {nat:"Norwegian Bokmål", code: "nb"},
    {nat:"Norwegian Nynorsk", code: "nn"},
    {nat:"Norwegian", code: "no"},
    {nat:"Sichuan Yi, Nuosu", code: "ii"},
    {nat:"South Ndebele", code: "nr"},
    {nat:"Occitan", code: "oc"},
    {nat:"Ojibwa", code: "oj"},
    {nat:"Church Slavic, Old Slavonic, Church Slavonic, Old Bulgarian, Old Church Slavonic", code: "cu"},
    {nat:"Oromo", code: "om"},
    {nat:"Oriya", code: "or"},
    {nat:"Ossetian, Ossetic", code: "os"},
    {nat:"Punjabi, Panjabi", code: "pa"},
    {nat:"Pali", code: "pi"},
    {nat:"Persian", code: "fa"},
    {nat:"Polish", code: "pl"},
    {nat:"Pashto, Pushto", code: "ps"},
    {nat:"Portuguese", code: "pt"},
    {nat:"Quechua", code: "qu"},
    {nat:"Romansh", code: "rm"},
    {nat:"Rundi", code: "rn"},
    {nat:"Romanian, Moldavian, Moldovan", code: "ro"},
    {nat:"Russian", code: "ru"},
    {nat:"Sanskrit", code: "sa"},
    {nat:"Sardinian", code: "sc"},
    {nat:"Sindhi", code: "sd"},
    {nat:"Northern Sami", code: "se"},
    {nat:"Samoan", code: "sm"},
    {nat:"Sango", code: "sg"},
    {nat:"Serbian", code: "sr"},
    {nat:"Gaelic, Scottish Gaelic", code: "gd"},
    {nat:"Shona", code: "sn"},
    {nat:"Sinhala, Sinhalese", code: "si"},
    {nat:"Slovak", code: "sk"},
    {nat:"Slovenian", code: "sl"},
    {nat:"Somali", code: "so"},
    {nat:"Southern Sotho", code: "st"},
    {nat:"Spanish, Castilian", code: "es"},
    {nat:"Sundanese", code: "su"},
    {nat:"Swahili", code: "sw"},
    {nat:"Swati", code: "ss"},
    {nat:"Swedish", code: "sv"},
    {nat:"Tamil", code: "ta"},
    {nat:"Telugu", code: "te"},
    {nat:"Tajik", code: "tg"},
    {nat:"Thai", code: "th"},
    {nat:"Tigrinya", code: "ti"},
    {nat:"Tibetan", code: "bo"},
    {nat:"Turkmen", code: "tk"},
    {nat:"Tagalog", code: "tl"},
    {nat:"Tswana", code: "tn"},
    {nat:"Tonga (Tonga Islands)", code: "to"},
    {nat:"Turkish", code: "tr"},
    {nat:"Tsonga", code: "ts"},
    {nat:"Tatar", code: "tt"},
    {nat:"Twi", code: "tw"},
    {nat:"Tahitian", code: "ty"},
    {nat:"Uighur, Uyghur", code: "ug"},
    {nat:"Ukrainian", code: "uk"},
    {nat:"Urdu", code: "ur"},
    {nat:"Uzbek", code: "uz"},
    {nat:"Venda", code: "ve"},
    {nat:"Vietnamese", code: "vi"},
    {nat:"Volapük", code: "vo"},
    {nat:"Walloon", code: "wa"},
    {nat:"Welsh", code: "cy"},
    {nat:"Wolof", code: "wo"},
    {nat:"Western Frisian", code: "fy"},
    {nat:"Xhosa", code: "xh"},
    {nat:"Yiddish", code: "yi"},
    {nat:"Yoruba", code: "yo"},
    {nat:"Zhuang, Chuang", code: "za"},
    {nat:"Zulu", code: "zu"}
]

export const currentYear = new Date().getFullYear()